snap: update to latest version
AlanGriffiths/cevelop-snap pull request #1
Opened 2019-08-07 13:24 UTC by Darnor

2019-08-07 14:50 UTC, AlanGriffiths requested changes

2019-08-07 14:50 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +version: 1.12.1-201907101456
I want to drive the version from the downloaded archive, so I don't like this approach.

2019-08-07 14:50 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +
Yes. I missed that it is an x86_64 archive.

2019-08-07 14:50 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +    source: https://www.cevelop.com/cevelop/downloads/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION-linux.gtk.x86_64.tar.gz
See above. I should probably try scraping https://www.cevelop.com/download/index.html Something along the lines of:
```plain
curl -s https://www.cevelop.com/download/ | sed -n 's!^.*href="/cevelop/downloads/cevelop-\([0-9.-]*\)-linux.gtk.x86_64.tar.gz.*!\1!p' -
```

2019-08-07 14:56 UTC, Darnor commented on snap/snapcraft.yaml
> +    source: https://www.cevelop.com/cevelop/downloads/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION-linux.gtk.x86_64.tar.gz
Sounds good. I'll update the PR.

2019-08-13 16:00 UTC, AlanGriffiths commented
@Darnor, I think this achieves both of our goals: https://github.com/AlanGriffiths/cevelop-snap/pull/2

2019-08-15 09:05 UTC, Darnor commented
> @Darnor, I think this achieves both of our goals: #2

Looks good. :+1:, thank you for your work.

2019-08-15 09:05 UTC, closed without merging